// <auto-generated />
namespace FinalPieShopTake1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Forignkeyrelationofpie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Forignkeyrelationofpie));
        
        string IMigrationMetadata.Id
        {
            get { return "202008281353382_Forign key relation of pie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
